title = "Bodhi Services"
baseURL = "http://www.bodhi.services"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "themes"


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Steve to change theme ....."
  facebook = ""
  twitter = "https://twitter.com/ServicesBodhi"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-grey"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = "/images/background.jpg"
  recent_posts_number = 2
